Update Prometheus metrics
ampproject/amppackager pull request #543
Opened 2021-07-08 11:32 UTC by SuperQ

This is an overhaul of the Prometheus metrics. The goal is to improve
usability by following best practices.

Use Histograms rather than summaries.
* Summaries can not be aggregated, this makes them unusable when you run
multiple instances of the service.
* Histograms provide the ability to use "heatmap" views of the data.

Drop counters that duplicate data we already have in the histogram `_count` metric.

Rename metrics to follow Prometheus naming conventions. For example,
prefixing custom metrics with the app name as a `Namespace`.

Related to https://github.com/ampproject/amppackager/issues/357

Signed-off-by: SuperQ <superq@gmail.com>

2021-07-08 11:32 UTC, SuperQ commented
CC @FranGM

2021-07-09 21:46 UTC, twifkak commented
Wow, thanks for this big improvement! Since it's backwards-incompatible (IIUC), I want to make sure our users are okay with it. I'd say we should block on an OK from @FranGM and nonblockingly notify `#signed-exchanges` on the AMP Slack. (I can do the latter.) If we get pushback, we may need a migration plan (e.g. flag flip?). Sound OK to you?

I'll take a look at the code now. (Pardon my naïveté in advance.)

2021-07-09 21:49 UTC, SuperQ commented
Yup, sounds fine. I'm an SRE working with @FranGM to get this working in our production environment.

Let me know if you have any questions.

2021-07-09 21:56 UTC, FranGM commented
Definitely happy with these changes getting merged!

2021-07-14 01:05 UTC, twifkak requested changes
This looks good to me; just a few nits.

2021-07-14 13:06 UTC, SuperQ commented on packager/mux/mux_test.go
> -			/* testName= */ `ErrorsReturnedByMuxDirectly`,
Ok, I added a 404 test for healthz.

But I do [see an unassigned test here](https://github.com/ampproject/amppackager/pull/543/files#diff-b2770040fb5051af4a97bd06ec2db6b0175f8cbe34082280dc41f10eb2d4ce47L448-L454).

2021-07-14 13:06 UTC, SuperQ commented
Updated with requested changes.

2021-07-15 17:50 UTC, twifkak commented on packager/mux/mux_test.go
> -			/* testName= */ `ErrorsReturnedByMuxDirectly`,
Ah good catch. I didn't click the down arrow enough in diff view. :facepalm:

2021-07-15 17:51 UTC, twifkak approved these changes
Thanks again for the improvements (and matching doc changes)! This looks good to me. I'll go ahead and merge now.

2021-07-15 17:51 UTC, merged

2021-07-15 18:11 UTC, twifkak commented
Addresses #357.