Add version information
ampproject/amppackager pull request #545
Opened 2021-07-10 04:34 UTC by SuperQ

Add a `-version` flag and metric to make it possible to monitor the
deployed version.

Signed-off-by: SuperQ <superq@gmail.com>

2021-07-10 04:37 UTC, SuperQ commented
CC @FranGM

2021-07-12 20:01 UTC, twifkak requested changes
Thanks for the contribution! This PR was an easier one for me to review (I have more context) so I'll reply to it first.

2021-07-12 21:32 UTC, SuperQ commented on cmd/amppkg/main.go
> +	prometheus.MustRegister(version.NewCollector("amppackager"))
This seems like it would be a separate info metric, not related to the build info.

2021-07-13 09:48 UTC, SuperQ commented
One note, with the current `go get` and `go install` commands, the `vendor` directory is never used. It downloads the modules live anyway.

Maybe it's time to drop the inline `vendor` dir?

2021-07-14 00:19 UTC, twifkak commented on README.md
> +       go get -u -ldflags "${version_flags}" github.com/ampproject/amppackager/cmd/amppkg
That sounds good to me! I like the idea of simplifying these instructions.

2021-07-14 00:20 UTC, twifkak commented on cmd/amppkg/main.go
> +	prometheus.MustRegister(version.NewCollector("amppackager"))
Yeah, feel free to mark this as resolved then. Totally optional.

2021-07-14 00:30 UTC, twifkak commented
> One note, with the current `go get` and `go install` commands, the `vendor` directory is never used. It downloads the modules live anyway.
> 
> Maybe it's time to drop the inline `vendor` dir?

Oh no, I thought I'd gotten this right finally. My apologies.

I'm torn. I like the `vendor` dir because:
 - It makes it obvious when we're increasing our binary size too much. (e.g. I made #394 in response to seeing a big addition to `vendor` in #349.)
 - It's easy-ish to scan our new dependencies and make sure they have OSS-compatible licenses.
 - It (ideally) confirms that the dependency versions in prod are the same as those tested by our CI.

But perhaps there's a better ways of doing these? (e.g. `go.{mod,sum}` is enough for the last one.)

I dislike `vendor` because:
 - It's big and weighs down our git repo and the GitHub UI.
 - Evidently I don't know how to use it.

2021-07-14 08:01 UTC, SuperQ commented
Yea, we finally gave up on the `vendor` dir in Promteheus. Go mod is good enough for most builds.

For point 1:  Yes, it does help with that. But you need to enforce a `go mod vendor && git diff --exit-code` to make sure that all PRs correctly update vendoring.

For point 2: For dependency scanning, you can call `go mod vendor` in CI. Works quite well.

For point 3: Go modules take care of this.

We have a pretty complex Makefile in Prometheus to take care of all the vendor stuff. It's partly complex because the vendoring method changed over the years. Today we've settled on using go.mod with no vendor dir. It's good enough.

2021-07-14 13:20 UTC, SuperQ commented
Ok, I've added a Makefile that will include the `-mod=vendor` flag if it's needed.

2021-07-15 18:02 UTC, twifkak reviewed
Thanks! One optional change before I merge. Feel free to punt and I'll merge as is.

2021-07-15 18:02 UTC, twifkak commented on README.md
> +  1. Optionally, move the built `amppkg` wherever you like.
Yeah nice to see this whole section simplified.

2021-07-15 18:09 UTC, twifkak commented
Created #549 for removing the vendor dir.

2021-07-15 18:11 UTC, twifkak commented
Addresses #357.

2021-07-15 18:16 UTC, SuperQ commented on Makefile
> +BRANCH    ?= $(shell git rev-parse --abbrev-ref HEAD)
I'm not sure what you mean? This gets the branch automatically, and isn't dependent on the workflow.

2021-07-15 18:16 UTC, SuperQ commented on Makefile
> +BRANCH    ?= $(shell git rev-parse --abbrev-ref HEAD)
Oh, you mean calling make in the workflow.

2021-07-15 18:33 UTC, twifkak approved these changes
Thanks! LGTM and the new actions succeed. Merging.

2021-07-15 18:34 UTC, merged